#!/bin/bash
URLLIST=$1
if [ -z $URLLIST ]
then
	echo -n "Enter the .csv file you wish to load entries from, leave blank for default (urllist.csv): "
	read URLLIST
	if [ -z $URLLIST ]
	then
        	CSV="urllist.csv"
	fi
fi
comment='#'
while read line
do
first=$(echo $line | cut -c 1)
	if [ $first == $comment ]
	then
		sleep 1
	else
		URL=$(echo $line | cut -d',' -f1)
		TIME=$(echo $line | cut -d',' -f2)
		EMAIL=$(echo $line | cut -d',' -f3)
		FILE=$(echo $line | cut -d',' -f4)
		echo "$FILE passed to clchecker"
		bash clchecker $URL $TIME $EMAIL $FILE &
	fi
done < "$URLLIST"
