#!/bin/bash
while [ 1 ]
do
URL=$1        
TIME=$2
EMAIL=$3
FILE=$4
curl -Os "$URL/$FILE.now" -A 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)'

if [[ -e "$FILE.now" && -e "$FILE.last" ]] 
then
    diff "$FILE.now" "$FILE.last"
    if [[ $? -ne 0 ]]; then
        echo "Page updated $URL This page will be checked again in $TIME seconds." | mail $EMAIL -s"Page \"$FILE\" updated"
        cp "$FILE.now" "$FILE.last"
    fi
else
    echo "Page added $URL This page will be checked again in $TIME seconds." | mail $EMAIL -s"Page \"$FILE\" added"
    cp "$FILE.now" "$FILE.last"
fi
sleep $TIME
done
