#!/bin/bash
echo -n "Enter the .csv file you wish this entry to be saved to, leave blank for default (urllist.csv): "
read CSV
if [ -z $CSV ]
then
        CSV="urllist.csv"
fi
echo -n "Please copy and paste the link for the page you want to check for changes: "
read URL
echo -n "Please enter the time in seconds desired between checks (5m=300, 30m=1800, 1h=3600, 6h=21600, 1d=86400 etc.,): "
read TIME
echo -n "Please enter the email address you want notifications sent to: "
read EMAIL
echo -n "Please enter a descriptive and unique name for the search (recommended is SiteLocationKeywordFilters): "
read FILE
echo -n "Enter the value for the ruleset you wish the search processed under, leave blank for default (0, no processing): "
read RULE
if [ -z $RULE ]
then
        RULE=0
fi
#if [ -n $URL || -n $TIME || -n $EMAIL || -n $FILE ]
#then
#	echo "Blank entries are not accepted for the url, time, email, or name. Aborting."
#else
pkill -f clchecker
echo "$URL,$TIME,$EMAIL,$FILE,$RULE" >> $CSV
bash checkstarter $CSV
#fi
